"""Change file_url to file_urls JSON array

Revision ID: 1be0d817a724
Revises: 8cf9a9ce466e
Create Date: 2025-11-21 10:53:15.749939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be0d817a724'
down_revision = '8cf9a9ce466e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('file_urls', sa.JSON(), nullable=True))
    op.drop_column('submission', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('submission', 'file_urls')
    # ### end Alembic commands ###
