"""Add image_url to Class

Revision ID: 1c5fd393fa39
Revises: d5b375b1dafc
Create Date: 2025-11-20 13:30:00.440556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5fd393fa39'
down_revision = 'd5b375b1dafc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('class', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('class', 'image_url')
    # ### end Alembic commands ###
