"""empty message

Revision ID: 3dd379ce091d
Revises: 71a2f30b5834
Create Date: 2025-11-22 03:35:07.806124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dd379ce091d'
down_revision = '71a2f30b5834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
