"""Add avatar_url to User model

Revision ID: 4c7bc4df6a8e
Revises: 1be0d817a724
Create Date: 2025-11-21 11:02:40.559033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7bc4df6a8e'
down_revision = '1be0d817a724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
