"""empty message

Revision ID: 5335b64b9152
Revises: 848a5fcb4dec
Create Date: 2025-11-22 02:55:18.817092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5335b64b9152'
down_revision = '848a5fcb4dec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
