"""Add avatar_url to User

Revision ID: 64427a036b43
Revises: 1c5fd393fa39
Create Date: 2025-11-21 09:32:47.326779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64427a036b43'
down_revision = '1c5fd393fa39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
