"""empty message

Revision ID: 69ea40525162
Revises: 3dd379ce091d
Create Date: 2025-11-22 03:43:03.286375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ea40525162'
down_revision = '3dd379ce091d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
