"""empty message

Revision ID: 71a2f30b5834
Revises: 5335b64b9152
Create Date: 2025-11-22 03:01:04.742797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a2f30b5834'
down_revision = '5335b64b9152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
