"""Add class_code to Class model

Revision ID: 848a5fcb4dec
Revises: 4c7bc4df6a8e
Create Date: 2025-11-22 02:47:37.426789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add class_code to Class model

Revision ID: 848a5fcb4dec
Revises: 4c7bc4df6a8e
Create Date: 2025-11-22 02:47:37.426789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848a5fcb4dec'
down_revision = '4c7bc4df6a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Data migration: Populate class_code for existing rows
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    
    # Check if column exists (it should based on the error, but let's be safe or just assume it does)
    # We'll just try to update.
    
    import random
    import string
    
    # Get all class IDs
    result = session.execute(sa.text("SELECT id FROM class"))
    classes = result.fetchall()
    
    for cls in classes:
        # Generate random 6-char code
        code = ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))
        # Update
        session.execute(
            sa.text("UPDATE class SET class_code = :code WHERE id = :id"),
            {"code": code, "id": cls.id}
        )
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('class', 'class_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'DEFAULT'::character varying"))
    op.drop_constraint(op.f('class_class_code_key'), 'class', type_='unique')
    op.drop_index(op.f('ix_class_class_code'), table_name='class')
    op.create_index(op.f('ix_class_class_code'), 'class', ['class_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_class_code'), table_name='class')
    op.create_index(op.f('ix_class_class_code'), 'class', ['class_code'], unique=False)
    op.create_unique_constraint(op.f('class_class_code_key'), 'class', ['class_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('class', 'class_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'DEFAULT'::character varying"))
    # ### end Alembic commands ###
