"""empty message

Revision ID: 90a3d5604cbf
Revises: ec95cde71abc
Create Date: 2025-11-22 05:27:18.150995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a3d5604cbf'
down_revision = 'ec95cde71abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
