"""fix_qa_schema

Revision ID: d5b375b1dafc
Revises: b41c82991d7b
Create Date: 2025-11-20 12:36:33.910263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b375b1dafc'
down_revision = 'b41c82991d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
