"""empty message

Revision ID: ec95cde71abc
Revises: 4a20a078b329
Create Date: 2025-11-22 05:22:30.706423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec95cde71abc'
down_revision = '4a20a078b329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
